"use client";
import React from "react";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
} from "chart.js";
import { Bar } from "react-chartjs-2";

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend
);

export const options = {
  responsive: true,
  plugins: {
    legend: {
      position: "top",
    },
    title: {
      display: true,
      text: "Répartition géographique des compétences par département",
    },
  },
};

const ChartRepartitionGeographique = () => {
  const labels = [
    "Dpt 1",
    "Dpt 2",
    "Dpt 3",
    "Dpt 4",
    "Dpt 5",
    "Dpt 6",
    "Dpt 7",
    "Dpt 8",
    "Dpt 9",
    "Dpt 10",
    "Dpt 11",
    "Dpt 12",
    "Dpt 13",
    "Dpt 14",
    "Dpt 15",
    "Dpt 16",
    "Dpt 17",
    "Dpt 18",
    "Dpt 19",
    "Dpt 20",
    "Dpt 21",
    "Dpt 22",
    "Dpt 23",
    "Dpt 24",
    "Dpt 25",
    "Dpt 26",
    "Dpt 27",
    "Dpt 28",
    "Dpt 29",
    "Dpt 30",
    "Dpt 31",
    "Dpt 32",
    "Dpt 33",
    "Dpt 34",
    "Dpt 35",
    "Dpt 36",
    "Dpt 37",
    "Dpt 38",
    "Dpt 39",
    "Dpt 40",
    "Dpt 41",
    "Dpt 42",
    "Dpt 43",
    "Dpt 44",
    "Dpt 45",
    "Dpt 46",
    "Dpt 47",
    "Dpt 48",
    "Dpt 49",
    "Dpt 50",
    "Dpt 51",
    "Dpt 52",
    "Dpt 53",
    "Dpt 54",
    "Dpt 55",
    "Dpt 56",
    "Dpt 57",
    "Dpt 58",
    "Dpt 59",
    "Dpt 60",
    "Dpt 61",
    "Dpt 62",
    "Dpt 63",
    "Dpt 64",
    "Dpt 65",
    "Dpt 66",
    "Dpt 67",
    "Dpt 68",
    "Dpt 69",
    "Dpt 70",
    "Dpt 71",
    "Dpt 72",
    "Dpt 73",
    "Dpt 74",
    "Dpt 75",
    "Dpt 76",
    "Dpt 77",
    "Dpt 78",
    "Dpt 79",
    "Dpt 80",
    "Dpt 81",
    "Dpt 82",
    "Dpt 83",
    "Dpt 84",
    "Dpt 85",
    "Dpt 86",
    "Dpt 87",
    "Dpt 88",
    "Dpt 89",
    "Dpt 90",
    "Dpt 91",
    "Dpt 92",
    "Dpt 93",
    "Dpt 94",
    "Dpt 95",
    "Hors France",
  ];

  function calculerSomme(dataArr) {
    return dataArr.reduce((acc, obj) => acc + obj.value, 0);
  }

  const dataArr = [
    { dpt: "1", value: 1 },
    { dpt: "2", value: 1 },
    { dpt: "3", value: 1 },
    { dpt: "4", value: 0 },
    { dpt: "5", value: 1 },
    { dpt: "6", value: 46 },
    { dpt: "7", value: 0 },
    { dpt: "8", value: 0 },
    { dpt: "9", value: 0 },
    { dpt: "10", value: 0 },
    { dpt: "11", value: 0 },
    { dpt: "12", value: 0 },
    { dpt: "13", value: 16 },
    { dpt: "14", value: 0 },
    { dpt: "15", value: 0 },
    { dpt: "16", value: 0 },
    { dpt: "17", value: 1 },
    { dpt: "18", value: 1 },
    { dpt: "19", value: 0 },
    { dpt: "20", value: 0 },
    { dpt: "21", value: 1 },
    { dpt: "22", value: 1 },
    { dpt: "23", value: 0 },
    { dpt: "24", value: 1 },
    { dpt: "25", value: 1 },
    { dpt: "26", value: 2 },
    { dpt: "27", value: 0 },
    { dpt: "28", value: 1 },
    { dpt: "29", value: 1 },
    { dpt: "30", value: 3 },
    { dpt: "31", value: 71 },
    { dpt: "32", value: 0 },
    { dpt: "33", value: 8 },
    { dpt: "34", value: 10 },
    { dpt: "35", value: 10 },
    { dpt: "36", value: 0 },
    { dpt: "37", value: 4 },
    { dpt: "38", value: 15 },
    { dpt: "39", value: 0 },
    { dpt: "40", value: 0 },
    { dpt: "41", value: 0 },
    { dpt: "42", value: 0 },
    { dpt: "43", value: 0 },
    { dpt: "44", value: 9 },
    { dpt: "45", value: 1 },
    { dpt: "46", value: 0 },
    { dpt: "47", value: 1 },
    { dpt: "48", value: 4 },
    { dpt: "49", value: 0 },
    { dpt: "50", value: 0 },
    { dpt: "51", value: 1 },
    { dpt: "52", value: 0 },
    { dpt: "53", value: 1 },
    { dpt: "54", value: 0 },
    { dpt: "55", value: 2 },
    { dpt: "56", value: 0 },
    { dpt: "57", value: 8 },
    { dpt: "58", value: 0 },
    { dpt: "59", value: 0 },
    { dpt: "60", value: 2 },
    { dpt: "61", value: 2 },
    { dpt: "62", value: 2 },
    { dpt: "63", value: 1 },
    { dpt: "64", value: 7 },
    { dpt: "65", value: 5 },
    { dpt: "66", value: 16 },
    { dpt: "67", value: 1 },
    { dpt: "68", value: 2 },
    { dpt: "69", value: 1 },
    { dpt: "70", value: 1 },
    { dpt: "71", value: 0 },
    { dpt: "72", value: 0 },
    { dpt: "73", value: 0 },
    { dpt: "74", value: 0 },
    { dpt: "75", value: 106 },
    { dpt: "76", value: 4 },
    { dpt: "77", value: 3 },
    { dpt: "78", value: 56 },
    { dpt: "79", value: 3 },
    { dpt: "80", value: 0 },
    { dpt: "81", value: 1 },
    { dpt: "82", value: 2 },
    { dpt: "83", value: 0 },
    { dpt: "84", value: 0 },
    { dpt: "85", value: 0 },
    { dpt: "86", value: 0 },
    { dpt: "87", value: 0 },
    { dpt: "88", value: 0 },
    { dpt: "89", value: 0 },
    { dpt: "90", value: 0 },
    { dpt: "91", value: 31 },
    { dpt: "92", value: 79 },
    { dpt: "93", value: 14 },
    { dpt: "94", value: 29 },
    { dpt: "95", value: 14 },
    { dpt: "Hors France", value: 101 },
  ];

  const somme = calculerSomme(dataArr);

  //last update 8/12/23
  const data = {
    labels: labels,
    datasets: [
      {
        label: "%",
        data: dataArr.map((dpt, index) =>
          ((dpt.value / somme) * 100).toFixed(2)
        ),
        backgroundColor: "#99C3FF",
      },
    ],
  };

  return (
    <div className="chart">
      <Bar options={options} data={data} />
    </div>
  );
};

export default ChartRepartitionGeographique;
